name: hsg_loyalty
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  http: ^1.1.0
  url_launcher: ^6.2.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  dio: ^5.3.4
  retrofit: ^4.0.3
  syncfusion_flutter_pdfviewer: ^26.1.38
  go_router: ^14.1.1
  device_preview:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.6


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icons/ic_launcher_qorgay-playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: #ffffff

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/jsons/
    - assets/images/
    - assets/icons/
    - assets/app_icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf